export const SERVICE_INIT = "SERVICE_INIT";
export const SERVICE_INITIALIZED = "SERVICE_INITIALIZED";
export const SERVICE_START = "SERVICE_START";
export const SERVICE_STARTED = "SERVICE_STARTED";
export const SERVICE_STOP = "SERVICE_STOP";
export const SERVICE_STOPPED = "SERVICE_STOPPED";
export const SERVICE_MSG_RECIEVED = "SERVICE_MSG_RECIEVED";
export const SERVICE_MSG_REQUEST = "SERVICE_MSG_REQUEST";
export const SERVICE_MSG_RESPONSE = "SERVICE_MSG_RESPONSE";
export const DISPATCH_ACTION = "DISPATCH_ACTION";

